/* ###*B*###
 *
 * ERIKA Enterprise - a tiny RTOS for small microcontrollers
 * 
 * Copyright (C) 2002-2018 Evidence Srl
 * 
 * This file is part of ERIKA Enterprise.
 * 
 * See LICENSE file.
 *
 * ###*E*### */

/***************************************************************************
 *
 * This file is generated by RT-Druid.
 * Please do not modify it.
 *
 **************************************************************************/

#ifndef OS_EE_RTD_OSCFG_H
#define OS_EE_RTD_OSCFG_H


/***************************************************************************
 *
 * Version Check
 *
 **************************************************************************/
#define OS_EE_RTD_GEN_VERSION 12345


/***************************************************************************
 *
 * Common defines
 *
 **************************************************************************/
#define OSEE_SINGLECORE
#define OsNumberOfCores         (1U)
#define OSEE_CORE_ID_VALID_MASK ((1U << 0))



/***************************************************************************
 *
 * User options
 *
 **************************************************************************/
#define OSEE_DEBUG
#define OSEE_ASSERT
#define OS_EE_APPL_BUILD_DEBUG
#define OS_EE_BUILD_DEBUG
#define EE_BUILD_SINGLE_ELF

/***************************************************************************
 *
 * Automatic options
 *
 **************************************************************************/
#define OSEE_ARCH_TRICORE
#define OSEE_CPU_CLOCK (200000000U)
#define OSEE_HAS_EVENTS
#define OSEE_HAS_RESOURCES
#define OSEE_ISR2_MAX_HW_ASM_PRIO 19
#define OSEE_ISR2_MAX_PRIO (146U)
#define OSEE_MONO_STACK
#define OSEE_OC_ECC2
#define OSEE_TC_CORE0_ISR_MAX_PRIO  (19U)
#define OSEE_TC_TC27X
#define OS_EE_GCC
#define OS_EE_KERNEL_OSEK
#define OS_EE_RTD_BUILD_ENV_CYGWIN


/***************************************************************************
 *
 * Automatic OS options
 *
 **************************************************************************/




/***************************************************************************
 *
 * ISR1 declaration
 *
 **************************************************************************/

/***************************************************************************
 *
 * ISR2 declaration
 *
 **************************************************************************/


#define OSEE_TC_CORE0_19_ISR_CAT (2U)
#define OSEE_TC_CORE0_19_ISR_TID 0

#define OSEE_TC_CORE0_asclin0TxISR_ISR_TID   (0U)
#define OSEE_TC_CORE0_asclin0TxISR_ISR_PRIO  (19U)



#define OSEE_TC_CORE0_2_ISR_CAT (2U)
#define OSEE_TC_CORE0_2_ISR_TID 1

#define OSEE_TC_CORE0_TimerISR_ISR_TID   (1U)
#define OSEE_TC_CORE0_TimerISR_ISR_PRIO  (2U)


/***************************************************************************
 *
 * System Timer
 *
 **************************************************************************/

/***************************************************************************
 *
 * End
 *
 **************************************************************************/
#endif /* OS_EE_RTD_OSCFG_H */

